name: CI

on:
  push:
    branches: [ staging, release ]
  pull_request:
    branches: [ main, staging, release ]  

  workflow_dispatch:

jobs:
  lint_core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Core
        run: |
            cd core
            docker-compose -f docker-compose.test.yml run sut npm run lint 

  test_core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Core
        run: |
            cd core
            docker-compose -f docker-compose.test.yml up --build --exit-code-from sut sut
